### ISSUE TITLE
Skill gem price is outdated

### ISSUE THREAD

**Issue by Veraokulo** [grummble-ai/PathOfExile-SkillGemMargins#10]
Data from poe.ninja for league 'Ancestor' from 07.09.2023, 01:41 GMT+2. Current divine price is 232.42 C.

**Comment by grummble-ai** [comment]
Thanks. Fixed.

**Comment by Veraokulo** [comment]
Data from poe.ninja for league 'Ancestor' from 22.09.2023, 09:45 GMT+2. Current divine price is 233.2 C.

**Comment by Veraokulo** [comment]
@grummble-ai
