### ISSUE TITLE
SKill Gem leveling helper data not updated

### ISSUE THREAD

**Issue by Ploxl** [grummble-ai/PathOfExile-SkillGemMargins#7]
https://poeacademy.streamlit.app/Skill_Gem_Leveling_Helper

still shows data from sanctum league, seems like it hasnt been updated to pull data from crucible league. Updatable?

**Comment by grummble-ai** [comment]
Fixed! I was getting the current league from the PoE api, but they've changed the order which is why the tool tried to grab ruthless SSF data from poe.ninja, which obviously didn't work.
